# @format

language: node_js
node_js:
  - 'stable'
cache:
directories:
  - 'node_modules'
script:
  - npm test
after_success:
  - npm run coverage
notifications:
  webhooks: https://coveralls.io/webhook
